# -*- coding: utf-8 -*-
"""PDFParsing_practice.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1d5W1zQk_oWRNap70btA3Pg_cqbhW3eTB

<a href="https://colab.research.google.com/github/AnshumanAryan24/Hackovation-2024-Project/blob/main/PDFParsing_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# PDF Text Parsing
From - https://medium.com/@Evenword/6-python-packages-for-working-with-pdf-files-5854c155ac8f

## Importing libraries
"""

from PyPDF2 import PdfReader

from flask import Flask, jsonify, request

"""## Loading Flask app the JS code will call"""

app = Flask(__name__)
@app.route('/pdfparsingtool', methods=['GET'])
def parse():
  PATH = request.args.get('number', default=1, type=str)
  reader = PdfReader(PATH)
  return jsonify({'pages': [page.extract_text() for page in reader.pages()]})
# meta = reader.metadata
# print("Total Pages: ", len(reader.pages))
# # All of the following could be None!
# print("Author: ", meta.author)
# print("Creator: ", meta.creator)
# print("Producer: ", meta.producer)
# print("Subject: ", meta.subject)
# print("Title: ", meta.title)

# if __name__ == '__main__':
#     app.run(debug=True, port=8800)

# !python -m waitress --port=5000 __name__:app

"""## Loading file"""

# PATH = "BCSE302P_DATABASE-SYSTEMS-LAB_LO_1.0_70_BCSE302P.pdf"
# reader = PdfReader(PATH)

"""## Printing parsing results"""

# pages = reader.pages
# for index, page in enumerate(pages):
#   print("\n\n\n------------------------")
#   print("PAGE ", index)
#   print(page.extract_text())